### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by Kawet00** [4lch4/Tron#188]
Where is the .env ?

**Comment by Rexogamer** [comment]
It's not a good idea to commit your `.env` file and most bot devs don't because it exposes sensitive tokens. To host this, you'd need to make your own (don't worry, it's pretty simple).

**Comment by Kawet00** [comment]
Thank you but the token which is on my github is a fake I have it reset the token just after

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by 4lch4** [comment]
Don't know how I missed this.. But @Rexogamer is correct. I don't commit the .env file as I'm not gonna share the token behind Tron.
